export const categories = [
  { href: "/jeans", name: "Keychron K1 Pro", imageUrl: "/60-1.jpg" },
  { href: "/t-shirts", name: "Keychron K6", imageUrl: "/60-1.jpg" },
  { href: "/shoes", name: "Keychron Q2", imageUrl: "/60-1.jpg" },
  { href: "/glasses", name: "Keychron V2", imageUrl: "/75-1.jpg" },
  { href: "/jackets", name: "Keychron K2", imageUrl: "/75-2.jpg" },
  { href: "/suits", name: "Keychron V1", imageUrl: "/75-3.jpg" },
  { href: "/bags", name: "Keychron C3", imageUrl: "/80-1.jpg" },
  { href: "/jackets", name: "Keychron K8", imageUrl: "/80-2.jpg" },
  { href: "/suits", name: "Keychron V3", imageUrl: "/80-3.jpg" },
  { href: "/bags", name: "Keychron V5", imageUrl: "/96-1.jpg" },
  { href: "/suits", name: "Keychron Q5 Pro", imageUrl: "/96-2.jpg" },
  { href: "/bags", name: "Keychron Q5", imageUrl: "/96-3.jpg" },
  { href: "/jackets", name: "Keychron C2", imageUrl: "/100-1.jpg" },
  { href: "/suits", name: "Keychron Q6", imageUrl: "/100-2.jpg" },
  { href: "/bags", name: "Keychron K5 SE", imageUrl: "/100-3.jpg" },
];
